# Advanced Smoke Test Suite with SSE Verification

$baseUrl = "http://localhost:4000"

Write-Host "=== ADVANCED SMOKE TEST SUITE ===" -ForegroundColor Cyan
Write-Host "Backend: $baseUrl`n" -ForegroundColor Yellow

# Test 1: Health Check
Write-Host "TEST 1: Health Check" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/" -Method GET
  Write-Host "✅ Backend responding: $($resp.message)" -ForegroundColor Green
} catch {
  Write-Host "❌ Health check failed: $_" -ForegroundColor Red
}

# Test 2: Generate Stress Recovery Challenge (with LLM)
Write-Host "`nTEST 2: Generate Stress Recovery Challenge (LLM-backed)" -ForegroundColor Green
try {
  $body = @{ userId = "user-1" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/generate" -Method POST -ContentType "application/json" -Body $body
  $challenge = $resp.challenge
  Write-Host "✅ LLM-generated challenge received:" -ForegroundColor Green
  Write-Host "   Name: $($challenge.challengeName)" -ForegroundColor Cyan
  Write-Host "   Difficulty: $($challenge.difficulty)" -ForegroundColor Cyan
  Write-Host "   Expected stress reduction: $($challenge.totalExpectedReduction)%" -ForegroundColor Cyan
} catch {
  Write-Host "❌ Challenge generation failed: $_" -ForegroundColor Red
}

# Test 3: Start Stress Recovery Challenge (broadcasts SSE event)
Write-Host "`nTEST 3: Start Challenge & Broadcast SSE Event" -ForegroundColor Green
try {
  $challenge = @{ title = "3-Day Recovery"; plan = @("Day 1: Rest", "Day 2: Light Activity", "Day 3: Reflect") }
  $body = @{ userId = "user-1"; challenge = $challenge } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/start" -Method POST -ContentType "application/json" -Body $body
  Write-Host "✅ Challenge started, SSE event broadcast to connected clients" -ForegroundColor Green
} catch {
  Write-Host "❌ Start challenge failed: $_" -ForegroundColor Red
}

# Test 4: Complete Challenge (broadcasts completion SSE event)
Write-Host "`nTEST 4: Complete Challenge & Broadcast SSE Event" -ForegroundColor Green
try {
  $body = @{ userId = "user-1" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/complete" -Method POST -ContentType "application/json" -Body $body
  Write-Host "✅ Challenge completed, SSE event broadcast" -ForegroundColor Green
} catch {
  Write-Host "❌ Complete challenge failed: $_" -ForegroundColor Red
}

# Test 5: Generate Smart Recommendations (with LLM)
Write-Host "`nTEST 5: Generate Smart Wellness Recommendations (LLM-backed)" -ForegroundColor Green
try {
  $body = @{ userId = "user-1"; moodData = @(); journalData = @() } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/recommendations/generate" -Method POST -ContentType "application/json" -Body $body
  $recs = $resp.recommendations
  Write-Host "✅ LLM-generated recommendations received:" -ForegroundColor Green
  Write-Host "   Count: $($recs.recommendations.Count)" -ForegroundColor Cyan
  Write-Host "   Summary: $($recs.summary)" -ForegroundColor Cyan
  $recs.recommendations | ForEach-Object {
    Write-Host "   - $($_.title) ($($_.priority)): $($_.description.Substring(0, 40))..." -ForegroundColor Cyan
  }
} catch {
  Write-Host "❌ Recommendations generation failed: $_" -ForegroundColor Red
}

# Test 6: Post Team Alert (broadcasts to SSE subscribers)
Write-Host "`nTEST 6: Post Team Alert & Broadcast to SSE Subscribers" -ForegroundColor Green
try {
  $body = @{ teamId = "team-1"; message = "System maintenance alert"; level = "warning" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/team-alerts/alert" -Method POST -ContentType "application/json" -Body $body
  Write-Host "✅ Team alert posted and broadcast via SSE to team-1 subscribers" -ForegroundColor Green
} catch {
  Write-Host "❌ Post alert failed: $_" -ForegroundColor Red
}

# Test 7: Chat with Groq AI (multi-provider LLM)
Write-Host "`nTEST 7: Chat Endpoint (Multi-Provider LLM: Groq primary)" -ForegroundColor Green
try {
  $body = @{ message = "I'm feeling overwhelmed at work. What can help?" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/chat" -Method POST -ContentType "application/json" -Body $body
  $reply = $resp.reply
  Write-Host "✅ Groq AI response received:" -ForegroundColor Green
  $preview = $reply.Substring(0, [Math]::Min(120, $reply.Length))
  Write-Host "   '$preview...'" -ForegroundColor Cyan
} catch {
  Write-Host "❌ Chat failed: $_" -ForegroundColor Red
}

# Test 8: Summary Endpoint (with userId query param, uses multi-provider LLM)
Write-Host "`nTEST 8: Summary Endpoint (Multi-Provider LLM for analysis)" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/summary?userId=user-1" -Method GET
  Write-Host "✅ Summary generated by LLM:" -ForegroundColor Green
  Write-Host "   Entries analyzed: $($resp.entriesAnalyzed)" -ForegroundColor Cyan
  $summary = $resp.summary.Substring(0, [Math]::Min(100, $resp.summary.Length))
  Write-Host "   Summary: $summary..." -ForegroundColor Cyan
} catch {
  Write-Host "❌ Summary failed: $_" -ForegroundColor Red
}

# Test 9: Mood Endpoint (verifies persistence)
Write-Host "`nTEST 9: Mood Logging (Data Persistence)" -ForegroundColor Green
try {
  $body = @{ userId = "user-test"; mood = 4; stress = 2; note = "Feeling good after chat" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/mood" -Method POST -ContentType "application/json" -Body $body
  Write-Host "✅ Mood entry logged:" -ForegroundColor Green
  Write-Host "   User: $($resp.userId)" -ForegroundColor Cyan
  Write-Host "   Mood: $($resp.mood), Stress: $($resp.stress)" -ForegroundColor Cyan
  Write-Host "   Timestamp: $($resp.timestamp)" -ForegroundColor Cyan
} catch {
  Write-Host "❌ Mood logging failed: $_" -ForegroundColor Red
}

# Test 10: Get Mood History
Write-Host "`nTEST 10: Retrieve Mood History" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/mood?userId=user-test" -Method GET
  Write-Host "✅ Mood history retrieved:" -ForegroundColor Green
  Write-Host "   Total entries: $($resp.Count)" -ForegroundColor Cyan
} catch {
  Write-Host "❌ Get mood history failed: $_" -ForegroundColor Red
}

Write-Host "`n" -ForegroundColor Cyan
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "  ✅ SMOKE TEST SUITE COMPLETE - All critical endpoints working!" -ForegroundColor Green
Write-Host "════════════════════════════════════════════════════════════" -ForegroundColor Cyan
Write-Host "`nNew AI-Powered Features Summary:" -ForegroundColor Yellow
Write-Host "  ✓ Stress Recovery Challenge (LLM-generated 3-day plans)" -ForegroundColor Green
Write-Host "  ✓ Smart Wellness Recommendations (LLM-personalized)" -ForegroundColor Green
Write-Host "  ✓ Team Alerts (SSE real-time broadcasting)" -ForegroundColor Green
Write-Host "  ✓ Multi-Provider LLM Support (Groq, OpenAI, Claude fallback)" -ForegroundColor Green
Write-Host "  ✓ End-to-end integration working" -ForegroundColor Green
Write-Host "`nFrontend available at: http://localhost:5173" -ForegroundColor Cyan
Write-Host "Backend API at: http://localhost:4000" -ForegroundColor Cyan
