$baseUrl = "http://localhost:4000"

Write-Host "=== ADVANCED SMOKE TEST SUITE ===" -ForegroundColor Cyan
Write-Host "Backend: $baseUrl" -ForegroundColor Yellow
Write-Host ""

Write-Host "TEST 1: Health Check" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/" -Method GET
  Write-Host "CHECK: Backend responding" -ForegroundColor Green
} catch {
  Write-Host "FAIL: Health check - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 2: Generate Stress Recovery Challenge (LLM)" -ForegroundColor Green
try {
  $body = @{ userId = "user-1" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/generate" -Method POST -ContentType "application/json" -Body $body
  $challenge = $resp.challenge
  Write-Host "PASS: LLM-generated challenge received" -ForegroundColor Green
  Write-Host ("  Name: " + $challenge.challengeName) -ForegroundColor Cyan
  Write-Host ("  Expected reduction: " + $challenge.totalExpectedReduction + "%") -ForegroundColor Cyan
} catch {
  Write-Host "FAIL: Challenge generation - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 3: Start Challenge - SSE Broadcast" -ForegroundColor Green
try {
  $body = @{ userId = "user-1"; challenge = @{ title = "Test" } } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/start" -Method POST -ContentType "application/json" -Body $body
  Write-Host "PASS: Challenge started, SSE event broadcast" -ForegroundColor Green
} catch {
  Write-Host "FAIL: Start challenge - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 4: Complete Challenge - SSE Broadcast" -ForegroundColor Green
try {
  $body = @{ userId = "user-1" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/stress-recovery/complete" -Method POST -ContentType "application/json" -Body $body
  Write-Host "PASS: Challenge completed, SSE event broadcast" -ForegroundColor Green
} catch {
  Write-Host "FAIL: Complete challenge - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 5: Generate Smart Recommendations (LLM)" -ForegroundColor Green
try {
  $body = @{ userId = "user-1" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/recommendations/generate" -Method POST -ContentType "application/json" -Body $body
  $recs = $resp.recommendations
  Write-Host "PASS: LLM-generated recommendations received" -ForegroundColor Green
  Write-Host ("  Count: " + $recs.recommendations.Count) -ForegroundColor Cyan
  Write-Host ("  Summary: " + $recs.summary) -ForegroundColor Cyan
} catch {
  Write-Host "FAIL: Recommendations - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 6: Post Team Alert - SSE Broadcast" -ForegroundColor Green
try {
  $body = @{ teamId = "team-1"; message = "Test alert"; level = "warning" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/team-alerts/alert" -Method POST -ContentType "application/json" -Body $body
  Write-Host "PASS: Team alert posted and broadcast via SSE" -ForegroundColor Green
} catch {
  Write-Host "FAIL: Post alert - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 7: Chat Endpoint (Multi-Provider LLM)" -ForegroundColor Green
try {
  $body = @{ message = "How can I manage work stress?" } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/chat" -Method POST -ContentType "application/json" -Body $body
  Write-Host "PASS: AI response received" -ForegroundColor Green
  $preview = $resp.reply.Substring(0, 80)
  Write-Host ("  Reply: " + $preview + "...") -ForegroundColor Cyan
} catch {
  Write-Host "FAIL: Chat - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 8: Summary Endpoint (Multi-Provider LLM)" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/summary?userId=user-1" -Method GET
  Write-Host "PASS: Summary generated by LLM" -ForegroundColor Green
  Write-Host ("  Entries analyzed: " + $resp.entriesAnalyzed) -ForegroundColor Cyan
} catch {
  Write-Host "FAIL: Summary - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 9: Mood Logging" -ForegroundColor Green
try {
  $body = @{ userId = "user-test"; mood = 4; stress = 2 } | ConvertTo-Json
  $resp = Invoke-RestMethod -Uri "$baseUrl/mood" -Method POST -ContentType "application/json" -Body $body
  Write-Host "PASS: Mood entry logged" -ForegroundColor Green
} catch {
  Write-Host "FAIL: Mood logging - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "TEST 10: Get Mood History" -ForegroundColor Green
try {
  $resp = Invoke-RestMethod -Uri "$baseUrl/mood?userId=user-test" -Method GET
  Write-Host "PASS: Mood history retrieved" -ForegroundColor Green
  Write-Host ("  Total entries: " + $resp.Count) -ForegroundColor Cyan
} catch {
  Write-Host "FAIL: Mood history - $_" -ForegroundColor Red
}

Write-Host ""
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host "SMOKE TEST COMPLETE - All critical AI features working!" -ForegroundColor Green
Write-Host "============================================================" -ForegroundColor Cyan
Write-Host ""
Write-Host "New AI-Powered Features:" -ForegroundColor Yellow
Write-Host "  Stress Recovery Challenge (LLM-generated 3-day plans)" -ForegroundColor Green
Write-Host "  Smart Wellness Recommendations (LLM-personalized)" -ForegroundColor Green
Write-Host "  Team Alerts (SSE real-time broadcasting)" -ForegroundColor Green
Write-Host "  Multi-Provider LLM Support (Groq primary, OpenAI fallback)" -ForegroundColor Green
Write-Host ""
Write-Host "Frontend: http://localhost:5173" -ForegroundColor Cyan
Write-Host "Backend:  http://localhost:4000" -ForegroundColor Cyan
